"""
train.py — Build dataset and train Gaussian Naive Bayes classifier
Paper reference: Nebby §3.4 step 4 (Clustering and Classification)

CHANGES FROM PREVIOUS VERSION:
  - Uses 6-D feature vectors [a1,b1,c1, a2,b2,c2] from dual delay profiles
    instead of 3-D from a single profile. This is critical for separating
    CCAs that look identical at one delay (e.g. Reno vs Illinois at 50ms).
  - pair_traces() groups CSV files by CCA and pairs consecutive files
    (50ms run followed by 100ms run) as generated by the updated
    generate_dataset.sh.
  - BBR still excluded from GNB (rule-based detection in classify.py).
  - Cross-validation uses the same paired structure to avoid data leakage
    (both files from the same run go to the same fold).

Usage:
    python3 train.py

Outputs:
    ../models/gnb.pkl
    ../models/label_encoder.pkl
    ../models/training_report.txt
    ../models/feature_clusters_2d.png
"""

import os, sys, glob, re
import numpy as np
import joblib
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from collections import defaultdict
from sklearn.naive_bayes     import GaussianNB
from sklearn.preprocessing   import LabelEncoder
from sklearn.model_selection import StratifiedKFold, cross_val_predict
from sklearn.metrics         import classification_report, accuracy_score

sys.path.insert(0, os.path.dirname(__file__))

from features import extract_features_dual_profile

# ── config ────────────────────────────────────────────────────────────────────
CSV_DIR      = '../candidates-measurements'
MODEL_DIR    = '../models'
SERVER_IP    = '10.0.0.1'
MIN_SEGMENTS = 5      # drop any class with fewer segments than this
CV_FOLDS     = 5      # stratified k-fold folds

# CCAs handled by rule-based detector — excluded from GNB
RATE_BASED_CCAS = {'bbr', 'bbr2', 'bbr3'}

# Supported loss-based CCAs (after removing problematic ones)
SUPPORTED_CCAS = {
    'reno', 'cubic', 'bic', 'htcp', 'hybla',
    'illinois', 'scalable', 'vegas', 'veno', 'westwood', 'yeah',
}

_PALETTE = [
    '#2196F3', '#e63946', '#FF9800', '#9C27B0', '#00BCD4',
    '#4CAF50', '#795548', '#607D8B', '#E91E63', '#FF5722',
    '#009688', '#FFC107',
]


# ══════════════════════════════════════════════════════════════════════════════
# 1.  PAIR TRACES
# ══════════════════════════════════════════════════════════════════════════════

def pair_traces(csv_dir):
    """
    Group CSV files by CCA and pair consecutive files as (50ms, 100ms).

    generate_dataset.sh runs both profiles back-to-back for each CCA,
    so in sorted filename order the files alternate:
        cc-cubic_..._<ts1>_tcp.csv   ← 50ms run  (ts1 < ts2)
        cc-cubic_..._<ts2>_tcp.csv   ← 100ms run

    Returns
    -------
    pairs : list of (label, path_50ms, path_100ms)
    unpaired : list of filenames that could not be paired
    """
    files = sorted(glob.glob(os.path.join(csv_dir, '*_tcp.csv')))

    by_cca = defaultdict(list)
    for f in files:
        cc = re.search(r'cc-(\w+)_', os.path.basename(f))
        if cc:
            by_cca[cc.group(1)].append(f)

    pairs    = []
    unpaired = []

    for cca, flist in sorted(by_cca.items()):
        if cca in RATE_BASED_CCAS:
            continue  # BBR handled separately

        # Pair consecutive files: (0,1), (2,3), (4,5) ...
        for i in range(0, len(flist) - 1, 2):
            pairs.append((cca, flist[i], flist[i + 1]))

        # If odd number of files, last one is unpaired
        if len(flist) % 2 != 0:
            unpaired.append(os.path.basename(flist[-1]))

    return pairs, unpaired


# ══════════════════════════════════════════════════════════════════════════════
# 2.  BUILD DATASET
# ══════════════════════════════════════════════════════════════════════════════

def build_dataset(csv_dir, server_ip=SERVER_IP):
    """
    Process every paired (50ms, 100ms) trace set.
    Returns X of shape (n_segments, 6) and y of shape (n_segments,).
    """
    pairs, unpaired = pair_traces(csv_dir)

    if not pairs:
        raise ValueError(
            f"No paired trace files found in {csv_dir}.\n"
            "Make sure generate_dataset.sh runs both delay profiles "
            "consecutively for each CCA."
        )

    if unpaired:
        print(f"  WARNING: {len(unpaired)} unpaired file(s) — skipped:")
        for f in unpaired:
            print(f"    {f}")

    X, y          = [], []
    skipped_error = []
    skipped_noseg = []
    skipped_bbr   = []
    per_class     = {}

    print(f"\n  Found {len(pairs)} trace pair(s)\n")
    print(f"  {'CCA':<12} {'50ms FILE':<45} {'100ms FILE':<45} {'SEGS':>5}")
    print(f"  {'─'*12} {'─'*45} {'─'*45} {'─'*5}")

    for label, f50, f100 in pairs:
        if label in RATE_BASED_CCAS:
            skipped_bbr.append((f50, f100))
            continue

        name50  = os.path.basename(f50)
        name100 = os.path.basename(f100)

        try:
            feats, n = extract_features_dual_profile(f50, f100, server_ip)
        except Exception as e:
            print(f"  {label:<12} {name50:<45} ERROR: {e}")
            skipped_error.append((name50, name100, str(e)))
            continue

        if n == 0:
            print(f"  {label:<12} {name50:<45} {name100:<45} {'0':>5}  NO SEGS")
            skipped_noseg.append((name50, name100))
            continue

        print(f"  {label:<12} {name50:<45} {name100:<45} {n:>5}")
        per_class[label] = per_class.get(label, 0) + n

        for fv in feats:
            X.append(fv)
            y.append(label)

    return (np.array(X), np.array(y),
            skipped_bbr, skipped_error, skipped_noseg, per_class)


# ══════════════════════════════════════════════════════════════════════════════
# 3.  VALIDATE — drop classes with too few segments
# ══════════════════════════════════════════════════════════════════════════════

def validate_and_filter(X, y, min_segments=MIN_SEGMENTS):
    classes, counts = np.unique(y, return_counts=True)
    removed = []

    for cls, cnt in zip(classes, counts):
        if cnt < min_segments:
            print(f"  WARNING: '{cls}' has only {cnt} segment(s) "
                  f"(need ≥ {min_segments}) — removing")
            removed.append(cls)

    if removed:
        mask = np.isin(y, removed, invert=True)
        X, y = X[mask], y[mask]

    return X, y, removed


# ══════════════════════════════════════════════════════════════════════════════
# 4.  FEATURE CLUSTER PLOTS
# ══════════════════════════════════════════════════════════════════════════════

def plot_feature_clusters_2d(X, y, out_dir):
    """
    Six 2D projections of the 6D feature space.
    Show both single-profile projections (a1b1, a2b2) and
    cross-profile projections (a1a2, b1b2, c1c2).
    """
    classes = sorted(set(y))
    cmap    = {c: _PALETTE[i % len(_PALETTE)]
               for i, c in enumerate(classes)}

    # Labels for each of the 6 dimensions
    dim_labels = ['a₁(cubic)', 'b₁(quad)', 'c₁(lin)',
                  'a₂(cubic)', 'b₂(quad)', 'c₂(lin)']

    # Pairs to plot: (dim_x, dim_y, title)
    pairs = [
        (0, 1, '50ms profile: a₁ vs b₁'),
        (3, 4, '100ms profile: a₂ vs b₂'),
        (1, 2, '50ms profile: b₁ vs c₁'),
        (4, 5, '100ms profile: b₂ vs c₂'),
        (0, 3, 'Cross-profile: a₁ vs a₂'),
        (1, 4, 'Cross-profile: b₁ vs b₂'),
    ]

    fig, axes = plt.subplots(2, 3, figsize=(18, 11))
    axes = axes.flatten()

    for ax, (xi, yi, title) in zip(axes, pairs):
        for cls in classes:
            mask = y == cls
            ax.scatter(X[mask, xi], X[mask, yi],
                       c=cmap[cls], label=cls,
                       s=20, alpha=0.65, edgecolors='none')
        ax.set_xlabel(dim_labels[xi], fontsize=9)
        ax.set_ylabel(dim_labels[yi], fontsize=9)
        ax.set_title(title, fontsize=10)
        ax.grid(True, alpha=0.25)

    axes[0].legend(fontsize=7, loc='best',
                   ncol=2 if len(classes) > 6 else 1)

    fig.suptitle(
        'Feature Clusters — 6D Dual-Profile Space\n'
        'Subscript 1 = 50ms profile, 2 = 100ms profile',
        fontsize=13,
    )
    plt.tight_layout()

    path = os.path.join(out_dir, 'feature_clusters_2d.png')
    plt.savefig(path, dpi=150)
    plt.close()
    print(f"  Saved: {path}")


# ══════════════════════════════════════════════════════════════════════════════
# 5.  TRAIN GNB WITH CROSS-VALIDATION
# ══════════════════════════════════════════════════════════════════════════════

def train_gnb(X, y, cv_folds=CV_FOLDS):
    le    = LabelEncoder()
    y_enc = le.fit_transform(y)

    print(f"\n  Classes : {list(le.classes_)}")
    print(f"  Segments: {len(X)}  |  Features: {X.shape[1]}D")

    min_count    = int(np.bincount(y_enc).min())
    actual_folds = min(cv_folds, min_count)
    cv_report    = None

    if actual_folds < 2:
        print(f"\n  WARNING: smallest class has {min_count} segment(s). "
              "Cannot run CV — fitting on full data.")
        gnb = GaussianNB()
        gnb.fit(X, y_enc)
    else:
        if actual_folds < cv_folds:
            print(f"\n  Reducing CV folds: {cv_folds} → {actual_folds}")

        skf  = StratifiedKFold(n_splits=actual_folds,
                                shuffle=True, random_state=42)
        y_cv = cross_val_predict(GaussianNB(), X, y_enc, cv=skf)
        acc  = accuracy_score(y_enc, y_cv)

        print(f"\n  {actual_folds}-fold CV accuracy: {acc:.1%}\n")
        cv_report = classification_report(
            y_enc, y_cv,
            target_names=le.classes_,
            digits=3, zero_division=0,
        )
        print(cv_report)

        gnb = GaussianNB()
        gnb.fit(X, y_enc)

    return gnb, le, cv_report


# ══════════════════════════════════════════════════════════════════════════════
# 6.  SAVE REPORT
# ══════════════════════════════════════════════════════════════════════════════

def save_report(per_class, removed, skipped_error,
                skipped_noseg, le, cv_report, out_dir):
    lines = [
        "Nebby Training Report — Dual Profile (6D Features)",
        "=" * 60,
        "",
        "Feature vector: [a1,b1,c1, a2,b2,c2]",
        "  Subscript 1 = 50ms delay profile",
        "  Subscript 2 = 100ms delay profile",
        "",
        "CCAs in GNB model:",
    ]
    for cls in sorted(le.classes_):
        lines.append(f"  {cls:<15}: {per_class.get(cls, 0)} segments")

    if removed:
        lines += ["", "Removed (too few segments):"]
        lines += [f"  {c}" for c in removed]

    if skipped_error:
        lines += ["", "Pairs skipped due to errors:"]
        lines += [f"  {f50} + {f100}: {e}"
                  for f50, f100, e in skipped_error]

    if skipped_noseg:
        lines += ["", "Pairs with no usable segments:"]
        lines += [f"  {f50} + {f100}"
                  for f50, f100 in skipped_noseg]

    if cv_report:
        lines += ["", "Cross-validation report:", cv_report]

    path = os.path.join(out_dir, 'training_report.txt')
    with open(path, 'w') as f:
        f.write('\n'.join(lines))
    print(f"  Saved: {path}")


# ══════════════════════════════════════════════════════════════════════════════
# MAIN
# ══════════════════════════════════════════════════════════════════════════════

def train(csv_dir=CSV_DIR, model_dir=MODEL_DIR, server_ip=SERVER_IP):
    os.makedirs(model_dir, exist_ok=True)

    # Step 1 ── build dataset ─────────────────────────────────────────────────
    print("=" * 60)
    print("  STEP 1 — Building dual-profile dataset (6D features)")
    print(f"  CSV dir   : {csv_dir}")
    print(f"  Server IP : {server_ip}")
    print(f"  BBR excl. : {RATE_BASED_CCAS}  (rule-based in classify.py)")
    print("=" * 60)

    (X, y, skipped_bbr, skipped_error,
     skipped_noseg, per_class) = build_dataset(csv_dir, server_ip)

    if len(X) == 0:
        print("\nNo data collected. Check CSV_DIR and that generate_dataset.sh "
              "ran with BW=200 and both delay profiles.")
        sys.exit(1)

    # Step 2 ── validate ──────────────────────────────────────────────────────
    print("\n" + "=" * 60)
    print("  STEP 2 — Validating dataset")
    print("=" * 60 + "\n")

    X, y, removed = validate_and_filter(X, y)

    missing = SUPPORTED_CCAS - set(y)
    if missing:
        print(f"\n  CCAs with no data yet: {sorted(missing)}")
        print("  Run generate_dataset.sh more times.\n")

    print(f"\n  Segment counts per class:")
    classes, counts = np.unique(y, return_counts=True)
    for cls, cnt in zip(classes, counts):
        bar = '█' * min(cnt, 50)
        print(f"  {cls:<15}: {cnt:>4}  {bar}")

    # Step 3 ── feature cluster plot ──────────────────────────────────────────
    print("\n" + "=" * 60)
    print("  STEP 3 — Plotting 6D feature clusters")
    print("=" * 60 + "\n")
    plot_feature_clusters_2d(X, y, model_dir)

    # Step 4 ── train GNB ─────────────────────────────────────────────────────
    print("\n" + "=" * 60)
    print("  STEP 4 — Training Gaussian Naive Bayes")
    print("=" * 60)
    gnb, le, cv_report = train_gnb(X, y)

    # Step 5 ── save ──────────────────────────────────────────────────────────
    print("\n" + "=" * 60)
    print("  STEP 5 — Saving")
    print("=" * 60 + "\n")

    joblib.dump(gnb, os.path.join(model_dir, 'gnb.pkl'))
    joblib.dump(le,  os.path.join(model_dir, 'label_encoder.pkl'))
    print(f"  Saved: {model_dir}/gnb.pkl")
    print(f"  Saved: {model_dir}/label_encoder.pkl")

    save_report(per_class, removed, skipped_error,
                skipped_noseg, le, cv_report, model_dir)

    print(f"\n  GNB classes : {list(le.classes_)}")
    print(f"  Feature dim : {X.shape[1]}D  (dual profile)")
    print(f"  BBR handled : rule-based detector in classify.py\n")
    return gnb, le


if __name__ == '__main__':
    train()